Add CloudSQL flag
google-github-actions/deploy-cloudrun pull request #244
Opened 2021-11-03 21:49 UTC by bkniffler

`--add-cloudsql-instances` as documented in https://cloud.google.com/sql/docs/mysql/connect-run#node.js

2021-11-03 21:53 UTC, bkniffler commented
@googlebot I signed it!

2021-11-10 17:40 UTC, averikitsch requested changes

2021-11-10 17:40 UTC, averikitsch commented on src/deploy-cloudrun.ts
> +        installBeta = true;
installBeta is unnecessary

2021-11-10 17:40 UTC, averikitsch commented on src/deploy-cloudrun.ts
> +      if (cloudsql) {
Add to line 100 that it will be ignored with metadata

2021-11-11 00:48 UTC, averikitsch reviewed
I apologize, I forgot to mention that you should remove the generated dist/index.js from the PR. This will be generated on merge.

2022-05-12 12:36 UTC, JeandeCampredon commented
Do you plan at some point to merge this ?

2022-07-29 19:54 UTC, averikitsch approved these changes

2022-07-29 19:59 UTC, averikitsch commented
Thank you for your patience. Can you resolve the merge conflict?

2022-08-22 12:35 UTC, nadavzipo commented
So this should be handled in with the cli/console at the moment?
Waiting as well.

2022-08-26 22:14 UTC, faizeev47 commented
Any update on this?

2022-08-29 09:49 UTC, FaizeKhan12 commented
Any update when this is coming in **google APIS SDK?**

2022-10-10 16:12 UTC, 178inaba commented
@bkniffler @averikitsch 
hello.
I tried to resolve the conflict in this pull request, but the configuration has changed, such as src/deploy-cloudrun.ts being deleted, so the conflict could not be resolved.
So I recreated a new pull request.
https://github.com/google-github-actions/deploy-cloudrun/pull/389

2022-10-16 09:53 UTC, vincejv commented
To anyone that can't wait for this PR to be merged, you can use the `flags` input to use the arguments that are currently not supported

```
flags:
    description: |-
      Space separated list of other Cloud Run flags, examples can be found:
      https://cloud.google.com/sdk/gcloud/reference/run/deploy#FLAGS. Ex
      --service-account=my-account@project.iam.gserviceaccount.com --concurrency=10
    required: false
```

Sample step would be for customizing the CPU and Memory during deployment
```
  - name: Deploy to Cloud Run
    id: deploy
    uses: google-github-actions/deploy-cloudrun@v0
    with:
      service: ${{ env.SERVICE }}
      region: ${{ env.REGION }}
      image: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.GHUB_REPO_NAME }}/${{ env.SERVICE }}:${{ github.sha }}
      project_id: ${{ env.PROJECT_ID }}
      flags: --cpu 1000m --memory 384Mi
```

Cheers!

2022-11-03 13:59 UTC, verbanicm commented
Closed as duplicate of #389

2022-11-03 13:59 UTC, closed without merging